sudo: required

services:
- docker

language: php

env:
  global:
  - REPO=ferfabricio/react-dev-docker
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: ob2CmRM46QQncfXM9FtY71X98U8bicJhf+UqLZqm/1sR0teKrCEVbUjYJMmbhFS1BJs8z5adWawMzgAsuy02gbttvJDFka9D+/VrVp4oSKK0QQncghdRV82UePGduQhs6XAd9AUNDjvDcqZBSaYtAkFr0LYU90Oy02VBzJNGLofwxPemRM6w/Sscfl7iO+UQWf096197MJB0Kp2RnegSg6KpBwC3ZFR6i5hYc94Jkqx4LYAudM6BBAVRCY9/LHBh4E0EIYtydo2WDeqYmvZMAm18oi95Wb4k3HI6vq/hHbzOHcMW5RwKYy7l/EdCB6Qy7gzPlfIS7Dv62B7XGMVIX6RYzbJjZNFYuVi91TYA74bc07XSnYgGRxv5wPsX26ChBcFDb1vcM+NaWY+gW25t+UHgsM+AP2YZE3l+Z/mks8sWtDkf33XnXy/mqKZNln2lTjCsigs+nhX2fjZHPz+VhfxOpqcMf9ICfbopPVOPyq3VpMYZgZIfoGkPVX/bsv4u1f4gEjQTiT+R1XqvRompNq2XhusBjXH1AYnlBmrqMkaR2HUBhQDWrV3a8OGHfWWmjZdv8oM67sz1l1O1E5g9Bppao9VXAbs44vL7MMunMWiDjO2i0ienwAXdeVW0JpO0mLWbvNjZZqBEi07tymF3i3A2b7vHVZMExCL2jNTounc=
  - secure: PvC6ngwMsAyC3cbfTrkdmATvswAKj/d2El9N1r9bVpw6UbmmpqJ6NRj+YLlKZNvh0D+/nrPV9bdzeyGtLFvWIRKE7xNKoo3NJvp/fpZdjiYrEcCxdZ1XtxVJzL2vP6NJ1OyG10ElUyfKdycfO1qpvy0SAfxPGffVbIl3wEn8Nu/n/QBIW3TvhSiWcdNFlovJMIEZIjOP2somvXpwx5dIUrsbmrJy5B6Qu9wIttPa2WCRlRn/b0Mn1Xlg6aiuZTSnSZD9L7qtmIDOwc4GxVSGyuo2ZFxn1qS4VO+BgYj6ZJp2kt9YXwhhsHUC868DXHzw1pEJoX9rNumchTqutuUUMq8yi+F3vVX3347hmYoO+SOv4aQ2623Z2m7gePTlFWzBrhQF9V+MgVM0NTJ60AdQShUKjEOArCwTMpFrxm6dLfoUxK8RxhdT0nqs62jYyI35f/+mj7RkXONDNOp4RgOEzlpFa49i3pxV75KcptTVlE4Kam3bQOAKXoF5bDpCWp71RVl1snBCJlZusjE94vxxiWrbgZ9QyG19++ekxBBJw02vJwTHiUnPQd4+bnCu31og6uyYFUJZxUVSNSzpnSeUN1REphcLB8mjNyNjKSFzMi6OYT5fE6c55I+vvI/RWUixfAdSvCNXmKWxgTBRbEhlwFOqzOn4vbGMIBz9TbvoGQU=
  - secure: f36sQHNDYK0v0o3+2AhiCPUBGnM/BLHIWDip9akHMYO9muzSL8qhDpCeK9plET8cOWvem+TRXp/VU7HVQLyGE7gZLqgqhV5FpGkt5IBp924Vyq35H8zrNxp0CMjr+03ioh7cvQErySEmZnCkX3fc4TsTgWc5CptPCKEop0F3pRMNquTBuyio4jlQ2GDocz1TOJFU+9JqqK/jQSdaAPkaUaxTmUmdb8GVus24FQNXPOoIiw49JFAT/jkB4LLyHfyNDQr3/WshfNvqjW8T2V8mDBXTgSV/Y0XMi+SUNSsoTVV36NsrdmstkWSN8xZPMl0LtxhPswlkaxz3PsU/GqzW4tuuSJPLhTF5BRBdCiyLkzy7Z2MPyFjmCPXPxAUnqyoLFyqLJkUHcCReWXCSIA/nveJeqctsc5iZaJpHqlg7j418Bfj1dVumTudfb4s9kJZQcI/Eg6ocLekRQsjCy/uGuZq02v0C/U4PpMT/AdE3RdQZIZi4lsPx5VLoRhd5dNPCK7T7/S3xsJTVri4JvA9Lb+ck1d9/K4iNVUyZ8m0ZTRYja6746ktYM3tX1xqiPrMioFNfnnDnr0ktEnqJNnrX5OOm3oP7NispRfhaCjS9EYplhdmeBi56ua9kKJ8yq/KmkvqhGVeNVzNmCaym34OTYtNTGXLwUQ3qa4YwmufOVHo=

install:
  - echo "install nothing!"

script:
- echo "Buildando imagem!"
- docker build -f Dockerfile -t $REPO:$COMMIT .

after_success:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO:$TAG
